import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import data from '../data/education.json'
import { useState } from 'react'
import Card from '../components/card'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  console.log(data);
  const [information, setInformation] = useState([...data]);

  return (
    <>
      <Head>
        <title>Departments of School</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/degree-icon.png"/>
      </Head>
      <main className={styles.main}>
        <div className={styles.degrees}>
          <div className=''
          <h1 className={styles.h1business}>Business Degrees</h1>
          {
            information && information.map((info, index) => {
              if (info.department === "Business") {
                return (
                  <Card key={index} degree={info.degree} colour="#98CE00" font="30px" />
                )
              }
            })
          }
          <h1>Computer Degrees</h1>
          {
            information && information.map((info, index) => {
              if (info.department === "Computing") {
                return (
                  <Card key={index} degree={info.degree} colour="#6CCFF6" font="30px" />
                )
              }
            })
          }
        </div>
      </main>
    </>
  )
}
